### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by subvertallchris** [mothepro/fancy-emitter#5]
Hi! I'm really enjoying your library and appreciate how nice your code looks. I saw it on Reddit and have been using it a bit since then. :-)

I just noticed that you released v2.0. Would you mind adding a CHANGELOG.md file or adding notes about releases to your tags? It'd help me figure out how to prioritize upgrades.

Thanks!

**Comment by mothepro** [comment]
Hey, great suggestion.

I'll try and get that up tonight. To summarize, the difference from 1.x and 2.x is the removal of the `SingleEmitter` & `SafeSingleEmitter` since that encourages the [`Deferred` anti-pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern). 

Glad you enjoy it :D

**Comment by mothepro** [comment]
Released [v2.0.0](https://github.com/mothepro/fancy-emitter/releases/tag/v2.0.0).

Feel free to reach out if you have any other concerns.
